"""Translation tables for the runtime operator surface."""

from __future__ import annotations

TRANSLATIONS = {
    "zh-CN": {
        "html_lang": "zh-CN",
        "title": "Governed Runtime 控制台",
        "runtime_root": "Runtime 根目录",
        "persistence": "持久化",
        "summary_aria": "Runtime 摘要",
        "tasks": "任务",
        "tasks_caption": "最近任务",
        "approvals": "审批",
        "approvals_caption": "待确认",
        "verification": "验证结果",
        "verification_caption": "验证记录",
        "attachments": "已接入仓库",
        "fail_closed_caption": "风险自动阻断",
        "workspace_overview": "控制台总览",
        "workspace_overview_caption": "所有日常入口集中在左侧操作台；这里只保留当前状态、账号配置和反馈证据的决策摘要。",
        "shortcut_entry": "推荐入口",
        "shortcut_entry_caption": "优先用这些入口完成日常闭环；页面按钮会通过同一个根目录入口执行。",
        "shortcut_fast": "日常快速反馈",
        "shortcut_fast_command": ".\\run.ps1 fast",
        "shortcut_fast_caption": "编码中先跑 build + quick feedback tests；不替代交付前 readiness。",
        "shortcut_daily": "交付 readiness",
        "shortcut_daily_command": ".\\run.ps1 readiness -OpenUi",
        "shortcut_daily_caption": "按 build -> test -> contract/invariant -> hotspot 收口并打开中文控制台。",
        "shortcut_targets": "目标仓巡检",
        "shortcut_targets_command": ".\\run.ps1 daily -Mode quick",
        "shortcut_targets_caption": "对 active targets 执行快速 daily flow。",
        "shortcut_rules": "规则漂移检查",
        "shortcut_rules_command": ".\\run.ps1 rules-check",
        "shortcut_rules_caption": "只检查 Codex/Claude/Gemini 规则漂移。",
        "shortcut_feedback": "功能反馈汇总",
        "shortcut_feedback_command": ".\\run.ps1 feedback",
        "shortcut_feedback_caption": "汇总 Codex/Claude 与 target-run 证据。",
        "run_now": "执行",
        "command_label": "命令",
        "open_surface": "打开面板",
        "surface_current": "当前面板",
        "runtime_surface_caption": "任务、执行输出、下一步建议和目标仓状态。",
        "codex_surface_caption": "当前账号、配置健康和额度快照。",
        "claude_surface_caption": "当前 Provider、凭据状态和本机配置入口。",
        "feedback_surface_caption": "闭环状态、证据新鲜度和处理建议。",
        "surface_loading": "正在加载摘要…",
        "surface_runtime_summary": "任务 {tasks} · 审批 {approvals} · 验证 {verification}",
        "surface_runtime_detail": "接入仓库 {attachments} · 风险阻断 {fail_closed}",
        "surface_runtime_action": "在此查看执行输出、历史和下一步建议。",
        "surface_codex_action": "去 Codex 面板查看账号详情和在线刷新。",
        "surface_claude_action": "去 Claude 面板查看 Provider 和推荐配置。",
        "surface_feedback_action": "去反馈面板查看证据、建议和详细报告。",
        "maintenance": "维护与升级",
        "stage": "阶段",
        "compatibility": "兼容性",
        "upgrade": "升级",
        "triage": "分流",
        "deprecation": "弃用",
        "retirement": "退役",
        "no_tasks": "暂无运行记录。",
        "no_attachments": "暂无已接入目标仓记录。",
        "task": "任务",
        "state": "状态",
        "goal": "目标",
        "outputs": "结果与记录",
        "run": "运行",
        "workspace": "工作区",
        "interaction": "交互",
        "rollback": "回滚",
        "repo": "仓库",
        "adapter": "接入方式",
        "diagnostics": "问题说明",
        "binding": "接入标识",
        "light_pack": "轻量上下文包",
        "fail_closed": "风险自动阻断",
        "preference": "默认方式",
        "gate_profile": "验证档位",
        "reason": "原因",
        "remediation": "修复建议",
        "missing": "缺失",
        "none": "无",
        "not_recorded": "未记录",
        "unknown_repo": "未知仓库",
        "actions": "统一操作台",
        "settings": "执行参数",
        "recommended_next": "AI 推荐下一步",
        "quick_actions": "本仓验证",
        "target_actions": "目标仓治理",
        "rule_actions": "规则与演进",
        "advanced_settings": "高级参数",
        "page_actions": "页面",
        "language": "语言",
        "target": "目标仓",
        "all_targets": "全部目标仓",
        "target_selection": "目标仓选择",
        "target_selection_hint": "默认全部；取消全部后可勾选多个目标仓。批量卸载只处理勾选目标。",
        "mode": "验证模式",
        "parallelism": "目标并发",
        "fail_fast": "失败即停",
        "dry_run": "只预演",
        "apply_removal": "真实执行清理/卸载",
        "apply_removal_hint": "全部功能应用默认删除已证明安全的退役托管文件；清理/卸载按钮需勾选才真实执行。只预演会禁用真实删除。",
        "milestone": "里程碑标签",
        "refresh": "刷新状态",
        "run": "执行",
        "command_output": "执行输出",
        "codex_console": "Codex 账号与配置",
        "codex_account": "账号",
        "codex_active": "当前",
        "codex_usage": "额度",
        "codex_usage_note": "额度说明",
        "codex_switch": "切换",
        "codex_delete": "删除",
        "codex_delete_confirm": "将先备份再删除这个本地 Codex 账号快照。不能删除当前正在使用的账号。继续执行？",
        "codex_sync_active": "同步快照",
        "codex_snapshot": "快照",
        "codex_snapshot_synced": "已与 {name} 同步",
        "codex_snapshot_drifted": "{name} 仍是旧快照，建议用当前登录状态回写",
        "codex_snapshot_missing": "当前活动账号还没有命名快照",
        "codex_sync_confirm": "将把当前 auth.json 覆盖回对应命名快照。继续执行？",
        "codex_sync_ok": "已同步当前账号快照。",
        "codex_open_usage": "打开官方 Usage",
        "codex_refresh": "刷新 Codex 状态",
        "codex_refresh_online": "强制在线刷新",
        "codex_refresh_online_hint": "会发起一次最小 Codex 在线请求，可能消耗极少量额度",
        "codex_refresh_idle": "当前显示本机最新快照。",
        "codex_refresh_ok": "在线刷新成功；当前显示最新在线快照。",
        "codex_refresh_fallback": "在线刷新失败；已回退到本机最新快照。",
        "codex_refresh_if_stale": "检测到额度快照过期时，会自动尝试在线刷新。",
        "codex_unknown_usage": "暂时无法读取额度信息",
        "codex_usage_freshness_stale": "额度快照已过期",
        "codex_usage_freshness_fresh": "额度快照较新",
        "codex_usage_freshness_unknown": "未记录刷新时间",
        "codex_config": "配置健康",
        "codex_recommended": "核心原则",
        "codex_current_choice": "当前实现",
        "codex_compact_policy": "压缩策略",
        "codex_manual_upgrade": "手动升档",
        "codex_recommended_note": "本项目长期优先遵循“综合效率优先”：少打扰、自动连续执行、节省 token / 成本、高效率。`gpt-5.5 + medium + never` 只是当前暂行实现；以后若模型、参数或技术栈更迭，应优先保持这个原则，而不是固化当前组合本身。",
        "codex_login": "登录状态",
        "codex_token_validity": "本地令牌",
        "codex_token_expiry": "登录令牌到期",
        "codex_token_note": "登录令牌到期只表示本地 Codex 登录凭据的 token 截止时间。",
        "codex_token_unknown": "未读取到本地 token 有效期",
        "codex_subscription_expiry": "套餐到期日",
        "codex_subscription_note": "套餐日期来自本地 token 声明，不是实时 billing API 查询。",
        "codex_subscription_unknown": "未读取到套餐有效期",
        "panel_cache_state": "数据状态",
        "panel_cache_cold": "首次加载中",
        "panel_cache_cached": "缓存快照",
        "panel_cache_refreshing": "后台刷新中",
        "panel_cache_ready": "已刷新",
        "panel_cache_error": "刷新失败",
        "codex_account_usage_unknown": "切换后可获取额度",
        "codex_usage_remaining": "余量",
        "codex_usage_reset": "重置",
        "claude_console": "Claude Provider 与配置",
        "claude_provider": "Provider",
        "claude_active": "当前",
        "claude_switch": "切换",
        "claude_delete": "删除",
        "claude_delete_confirm": "将先备份 provider-profiles.json，再删除这个本地 Claude Provider 配置。当前 Provider 不能删除，凭据不会被删除。继续执行？",
        "claude_refresh": "刷新 Claude 状态",
        "claude_optimize_preview": "预演推荐配置",
        "claude_optimize_apply": "应用推荐配置",
        "claude_view_settings": "查看 settings.json",
        "claude_view_profiles": "查看 provider-profiles.json",
        "claude_view_switcher": "查看切换脚本",
        "claude_service": "服务地址",
        "claude_models": "模型",
        "claude_extensions": "扩展能力",
        "claude_usage_note": "额度说明",
        "claude_settings_summary": "本机设置",
        "claude_config": "配置健康",
        "claude_command": "CLI 状态",
        "claude_mcp": "MCP 状态",
        "claude_settings": "本机设置",
        "claude_credential": "凭据",
        "claude_usage": "额度",
        "claude_unknown_usage": "暂时无法读取额度信息",
        "claude_active_provider": "当前 Provider",
        "claude_active_summary": "当前映射",
        "claude_context_strategy": "上下文策略",
        "claude_timeout": "超时",
        "claude_subagent": "子代理",
        "claude_note": "建议",
        "claude_local_files": "本机入口",
        "claude_file_hint": "只开放本机 Claude 配置相关文件预览，不开放任意系统路径读取。",
        "claude_provider_profiles": "Provider 配置",
        "claude_missing_credential": "缺少凭据",
        "claude_credential_ready": "凭据已就绪",
        "claude_apply_recommended_confirm": "将按当前激活 provider 备份并写入 Claude Code 推荐配置。继续执行？",
        "claude_no_active_provider": "当前未识别到激活 provider",
        "history": "执行历史",
        "no_history": "暂无执行历史。",
        "clear_history": "清空历史",
        "runtime_view": "Runtime",
        "feedback_view": "反馈",
        "codex_view": "Codex",
        "claude_view": "Claude",
        "feedback_console": "功能反馈闭环",
        "feedback_refresh": "刷新反馈摘要",
        "feedback_status": "反馈状态",
        "feedback_generated_at": "生成时间",
        "feedback_summary_caption": "简版摘要",
        "feedback_dimensions": "维度状态",
        "feedback_recommendations": "优化建议",
        "feedback_latest_runs": "最新目标仓证据",
        "feedback_latest_runs_hint": "看这 3 项就够了：接入方式是否正常、闭环状态是否 ready、写入状态是否真的执行过。",
        "feedback_repo_attach": "接入方式",
        "feedback_repo_flow": "运行流",
        "feedback_repo_closure": "闭环状态",
        "feedback_repo_write": "写入状态",
        "feedback_repo_attach_native": "原生直连",
        "feedback_repo_attach_bridge": "桥接接入",
        "feedback_repo_attach_manual": "人工接力",
        "feedback_repo_flow_live": "宿主内直接运行",
        "feedback_repo_flow_bridge": "通过桥接运行",
        "feedback_repo_closure_ready": "已具备闭环",
        "feedback_repo_closure_partial": "闭环未完成",
        "feedback_repo_write_unknown": "未记录写入执行",
        "feedback_repo_write_done": "已执行写入",
        "feedback_links": "文档与报告",
        "feedback_open_report": "查看详细报告",
        "feedback_open_guide": "查看反馈指南",
        "feedback_open_guide_en": "查看英文指南",
        "feedback_report_missing": "尚未生成详细报告，可先执行“功能反馈汇总”。",
        "feedback_loading": "正在加载反馈摘要…",
        "feedback_empty": "暂未获取到反馈摘要。",
        "feedback_preview": "文档预览",
        "feedback_preview_idle": "点击“查看详细报告”或“查看反馈指南”后，会在这里展开内容。",
        "ready": "就绪",
        "running": "执行中",
        "static_snapshot": "只读快照",
        "targets_action": "目标仓列表",
        "fast_feedback_action": "快速反馈",
        "readiness_action": "本仓 readiness",
        "rules_dry_run_action": "只查规则漂移",
        "rules_apply_action": "同步规则文件",
        "governance_baseline_action": "下发治理基线",
        "daily_all_action": "运行 Daily 巡检",
        "apply_all_action": "应用全部治理能力",
        "cleanup_targets_action": "一键清理退役文件",
        "uninstall_governance_action": "一键卸载治理",
        "feedback_report_action": "功能反馈汇总",
        "evolution_review_action": "演进候选预演",
        "experience_review_action": "经验沉淀预演",
        "evolution_materialize_action": "物化演进候选",
        "core_principle_action": "核心原则候选",
        "view_ref": "查看",
        "confirm_mutating": "该操作会应用目标仓治理能力，并默认删除已证明安全的退役托管文件；不安全候选会阻断。继续执行？",
        "confirm_evolution_materialize": "将把低风险演进候选物化为 proposal 或禁用态 skill candidate，不启用技能。继续执行？",
        "confirm_managed_cleanup": "将对选中的目标仓执行退役治理文件清理；未勾选“实际删除”时只预演。继续执行？",
        "confirm_governance_uninstall": "将对选中的目标仓执行治理卸载；勾选“实际删除”会删除或修补受管文件并写备份。继续执行？",
        "no_target_selected": "至少选择一个目标仓。",
        "interactive_required": "当前是静态快照；启动本地服务后可执行操作。",
    },
    "en": {
        "html_lang": "en",
        "title": "Governed Runtime Console",
        "runtime_root": "Runtime root",
        "persistence": "Persistence",
        "summary_aria": "Runtime Summary",
        "tasks": "Tasks",
        "tasks_caption": "recent tasks",
        "approvals": "Approvals",
        "approvals_caption": "waiting",
        "verification": "Verification",
        "verification_caption": "verification records",
        "attachments": "Attachments",
        "fail_closed_caption": "risk auto-block",
        "workspace_overview": "Workbench Overview",
        "workspace_overview_caption": "All daily entrypoints live in the left operator bench; this overview keeps only decision-grade status, account config, and feedback evidence.",
        "shortcut_entry": "Recommended Entrypoints",
        "shortcut_entry_caption": "Use these entrypoints for routine closure; page buttons delegate through the same repository-root command.",
        "shortcut_fast": "Daily fast feedback",
        "shortcut_fast_command": ".\\run.ps1 fast",
        "shortcut_fast_caption": "Run build plus quick feedback tests while coding; delivery still needs readiness.",
        "shortcut_daily": "Delivery readiness",
        "shortcut_daily_command": ".\\run.ps1 readiness -OpenUi",
        "shortcut_daily_caption": "Close with build -> test -> contract/invariant -> hotspot and open the console.",
        "shortcut_targets": "Target sweep",
        "shortcut_targets_command": ".\\run.ps1 daily -Mode quick",
        "shortcut_targets_caption": "Run quick daily flow for active targets.",
        "shortcut_rules": "Rule drift check",
        "shortcut_rules_command": ".\\run.ps1 rules-check",
        "shortcut_rules_caption": "Check Codex/Claude/Gemini rule drift only.",
        "shortcut_feedback": "Feedback summary",
        "shortcut_feedback_command": ".\\run.ps1 feedback",
        "shortcut_feedback_caption": "Summarize Codex/Claude and target-run evidence.",
        "run_now": "Run",
        "command_label": "Command",
        "open_surface": "Open panel",
        "surface_current": "Current panel",
        "runtime_surface_caption": "Tasks, execution output, next-work recommendation, and target state.",
        "codex_surface_caption": "Active account, config health, and usage snapshot.",
        "claude_surface_caption": "Active provider, credential status, and local config entrypoints.",
        "feedback_surface_caption": "Closure status, evidence freshness, and recommendations.",
        "surface_loading": "Loading summary...",
        "surface_runtime_summary": "Tasks {tasks} · Approvals {approvals} · Verification {verification}",
        "surface_runtime_detail": "Attachments {attachments} · Fail-closed {fail_closed}",
        "surface_runtime_action": "Use Runtime for output, history, and next-work decisions.",
        "surface_codex_action": "Open Codex for account detail and online refresh.",
        "surface_claude_action": "Open Claude for provider status and recommended config.",
        "surface_feedback_action": "Open Feedback for evidence, recommendations, and reports.",
        "maintenance": "Maintenance and Upgrade",
        "stage": "Stage",
        "compatibility": "Compatibility",
        "upgrade": "Upgrade",
        "triage": "Triage",
        "deprecation": "Deprecation",
        "retirement": "Retirement",
        "no_tasks": "No runtime activity has been recorded.",
        "no_attachments": "No attached target repos recorded.",
        "task": "Task",
        "state": "State",
        "goal": "Goal",
        "outputs": "Results",
        "run": "Run",
        "workspace": "Workspace",
        "interaction": "Interaction",
        "rollback": "Rollback",
        "repo": "Repo",
        "adapter": "Connection",
        "diagnostics": "Issue details",
        "binding": "Connection ID",
        "light_pack": "Light context pack",
        "fail_closed": "Fail closed",
        "preference": "Preference",
        "gate_profile": "Gate profile",
        "reason": "Reason",
        "remediation": "Remediation",
        "missing": "missing",
        "none": "none",
        "not_recorded": "not recorded",
        "unknown_repo": "unknown repo",
        "actions": "Unified Operator Bench",
        "settings": "Run Parameters",
        "recommended_next": "AI Recommended Next Step",
        "quick_actions": "Repo Verification",
        "target_actions": "Target Governance",
        "rule_actions": "Rules and Evolution",
        "advanced_settings": "Advanced Parameters",
        "page_actions": "Page",
        "language": "Language",
        "target": "Target repo",
        "all_targets": "All targets",
        "target_selection": "Target selection",
        "target_selection_hint": "All targets are selected by default. Clear all to choose multiple specific target repos.",
        "mode": "Mode",
        "parallelism": "Target parallelism",
        "fail_fast": "Fail fast",
        "dry_run": "Dry run",
        "apply_removal": "Apply cleanup/uninstall deletes",
        "apply_removal_hint": "Apply-all deletes proven-safe retired managed files by default; cleanup/uninstall buttons require this checkbox. Dry run disables deletes.",
        "milestone": "Milestone tag",
        "refresh": "Refresh status",
        "run": "Run",
        "command_output": "Execution output",
        "codex_console": "Codex Account and Config",
        "codex_account": "Account",
        "codex_active": "Active",
        "codex_usage": "Usage",
        "codex_usage_note": "Usage details",
        "codex_switch": "Switch",
        "codex_delete": "Delete",
        "codex_delete_confirm": "This backs up and deletes the local Codex auth snapshot. The active account cannot be deleted. Continue?",
        "codex_sync_active": "Sync snapshot",
        "codex_snapshot": "Snapshot",
        "codex_snapshot_synced": "Synced with {name}",
        "codex_snapshot_drifted": "{name} is stale; save the current login back into it",
        "codex_snapshot_missing": "The current active account has no named snapshot yet",
        "codex_sync_confirm": "This will overwrite the named auth snapshot with the current auth.json. Continue?",
        "codex_sync_ok": "Saved the current account snapshot.",
        "codex_open_usage": "Open Usage",
        "codex_refresh": "Refresh Codex",
        "codex_refresh_online": "Force online refresh",
        "codex_refresh_online_hint": "Runs a minimal Codex online request and may consume a small amount of quota",
        "codex_refresh_idle": "Showing the latest local snapshot.",
        "codex_refresh_ok": "Online refresh succeeded; showing the latest online snapshot.",
        "codex_refresh_fallback": "Online refresh failed; fell back to the latest local snapshot.",
        "codex_refresh_if_stale": "Automatically tries an online refresh when the usage snapshot is stale.",
        "codex_unknown_usage": "Usage information is not available yet",
        "codex_usage_freshness_stale": "Usage snapshot is stale",
        "codex_usage_freshness_fresh": "Usage snapshot is fresh",
        "codex_usage_freshness_unknown": "Refresh time not recorded",
        "codex_config": "Config health",
        "codex_recommended": "Core principle",
        "codex_current_choice": "Current implementation",
        "codex_compact_policy": "Compact policy",
        "codex_manual_upgrade": "Manual upgrade",
        "codex_recommended_note": "This project keeps the long-lived principle of efficiency first: low interruption, continuous execution, lower token and cost burn, and high throughput. `gpt-5.5 + medium + never` is only the current implementation. When future models, parameters, or tooling change, preserve that principle first rather than freezing the current combo itself.",
        "codex_login": "Login status",
        "codex_token_validity": "Local token",
        "codex_token_expiry": "Sign-in token expiry",
        "codex_token_note": "Sign-in token expiry only reflects the local Codex credential token lifetime.",
        "codex_token_unknown": "Local token expiry is not available",
        "codex_subscription_expiry": "Plan renewal date",
        "codex_subscription_note": "Plan dates come from local token claims, not a live billing API query.",
        "codex_subscription_unknown": "Plan validity is not available",
        "panel_cache_state": "Data status",
        "panel_cache_cold": "Loading for the first time",
        "panel_cache_cached": "Cached snapshot",
        "panel_cache_refreshing": "Refreshing in background",
        "panel_cache_ready": "Refreshed",
        "panel_cache_error": "Refresh failed",
        "codex_account_usage_unknown": "Switch to this account to fetch usage",
        "codex_usage_remaining": "left",
        "codex_usage_reset": "reset",
        "claude_console": "Claude Provider and Config",
        "claude_provider": "Provider",
        "claude_active": "Active",
        "claude_switch": "Switch",
        "claude_delete": "Delete",
        "claude_delete_confirm": "This backs up provider-profiles.json and deletes the local Claude provider profile. The active provider cannot be deleted and credentials are not removed. Continue?",
        "claude_refresh": "Refresh Claude",
        "claude_optimize_preview": "Preview recommended config",
        "claude_optimize_apply": "Apply recommended config",
        "claude_view_settings": "View settings.json",
        "claude_view_profiles": "View provider-profiles.json",
        "claude_view_switcher": "View switcher script",
        "claude_service": "Service",
        "claude_models": "Models",
        "claude_extensions": "Extensions",
        "claude_usage_note": "Usage",
        "claude_settings_summary": "Settings",
        "claude_config": "Config health",
        "claude_command": "CLI status",
        "claude_mcp": "MCP status",
        "claude_settings": "Local settings",
        "claude_credential": "Credential",
        "claude_usage": "Usage",
        "claude_unknown_usage": "Usage information is not available yet",
        "claude_active_provider": "Active provider",
        "claude_active_summary": "Current mapping",
        "claude_context_strategy": "Context strategy",
        "claude_timeout": "Timeout",
        "claude_subagent": "Subagent",
        "claude_note": "Recommendation",
        "claude_local_files": "Local entrypoints",
        "claude_file_hint": "Only Claude-related local config files are previewable here; arbitrary system files stay blocked.",
        "claude_provider_profiles": "Provider profiles",
        "claude_missing_credential": "missing credential",
        "claude_credential_ready": "credential ready",
        "claude_apply_recommended_confirm": "This will back up and write the recommended Claude Code config for the active provider. Continue?",
        "claude_no_active_provider": "no active provider detected",
        "history": "Run history",
        "no_history": "No run history.",
        "clear_history": "Clear history",
        "runtime_view": "Runtime",
        "feedback_view": "Feedback",
        "codex_view": "Codex",
        "claude_view": "Claude",
        "feedback_console": "Host Feedback Loop",
        "feedback_refresh": "Refresh feedback summary",
        "feedback_status": "Feedback status",
        "feedback_generated_at": "Generated at",
        "feedback_summary_caption": "Snapshot summary",
        "feedback_dimensions": "Dimension status",
        "feedback_recommendations": "Recommendations",
        "feedback_latest_runs": "Latest target evidence",
        "feedback_latest_runs_hint": "Focus on the adapter, closure state, and whether a write step actually ran.",
        "feedback_repo_attach": "Adapter",
        "feedback_repo_flow": "Flow",
        "feedback_repo_closure": "Closure",
        "feedback_repo_write": "Write",
        "feedback_repo_attach_native": "native attach",
        "feedback_repo_attach_bridge": "bridge attach",
        "feedback_repo_attach_manual": "manual handoff",
        "feedback_repo_flow_live": "live host run",
        "feedback_repo_flow_bridge": "bridge run",
        "feedback_repo_closure_ready": "closure ready",
        "feedback_repo_closure_partial": "closure incomplete",
        "feedback_repo_write_unknown": "write not recorded",
        "feedback_repo_write_done": "write executed",
        "feedback_links": "Docs and reports",
        "feedback_open_report": "Open detailed report",
        "feedback_open_guide": "Open zh-CN guide",
        "feedback_open_guide_en": "Open English guide",
        "feedback_report_missing": "No detailed report yet. Run the feedback summary action first.",
        "feedback_loading": "Loading feedback summary...",
        "feedback_empty": "Feedback summary is not available yet.",
        "feedback_preview": "Preview",
        "feedback_preview_idle": "Open the detailed report or guide to preview the content here.",
        "ready": "Ready",
        "running": "Running",
        "static_snapshot": "Read-only snapshot",
        "targets_action": "View targets",
        "fast_feedback_action": "Fast feedback",
        "readiness_action": "Check repo status",
        "rules_dry_run_action": "Rule drift check",
        "rules_apply_action": "Sync rules",
        "governance_baseline_action": "Apply governance baseline",
        "daily_all_action": "Run Daily sweep",
        "apply_all_action": "Apply all governance",
        "cleanup_targets_action": "Clean retired files",
        "uninstall_governance_action": "Uninstall governance",
        "feedback_report_action": "Feedback summary",
        "evolution_review_action": "Evolution dry run",
        "experience_review_action": "Experience dry run",
        "evolution_materialize_action": "Materialize evolution candidates",
        "core_principle_action": "Core-principle candidates",
        "view_ref": "View",
        "confirm_mutating": "This applies target governance and deletes proven-safe retired managed files by default; unsafe candidates are blocked. Continue?",
        "confirm_evolution_materialize": "This materializes low-risk evolution candidates as proposals or disabled skill candidates. It does not enable skills. Continue?",
        "confirm_managed_cleanup": "Run retired governance file cleanup for the selected targets. It only dry-runs unless apply removal is enabled. Continue?",
        "confirm_governance_uninstall": "Run governance uninstall for the selected targets. Apply removal deletes or patches managed files and writes backups. Continue?",
        "no_target_selected": "Select at least one target repo.",
        "interactive_required": "This is a static snapshot; start the local service to run actions.",
    },
}
