"""Translation tables for the runtime operator surface."""

from __future__ import annotations

TRANSLATIONS = {
    "zh-CN": {
        "html_lang": "zh-CN",
        "title": "治理运行时操作台",
        "runtime_root": "Runtime 根目录",
        "persistence": "持久化",
        "summary_aria": "Runtime 摘要",
        "tasks": "任务",
        "tasks_caption": "最近任务",
        "approvals": "审批",
        "approvals_caption": "待确认",
        "verification": "验证结果",
        "verification_caption": "验证记录",
        "stage_metric_caption": "维护阶段",
        "attachments": "已接入仓库",
        "fail_closed_caption": "风险自动阻断",
        "workspace_overview": "操作台总览",
        "workspace_overview_caption": "左侧执行，这里只看关键状态。",
        "shortcut_entry": "推荐入口",
        "shortcut_entry_caption": "优先用这些入口完成 repo-local 日常闭环；页面按钮会通过同一个根目录入口执行。",
        "shortcut_fast": "日常快速反馈",
        "shortcut_fast_command": ".\\run.ps1 fast",
        "shortcut_fast_caption": "编码中先跑 build + quick feedback tests；不替代交付前 readiness。",
        "shortcut_daily": "交付 readiness",
        "shortcut_daily_command": ".\\run.ps1 readiness -OpenUi",
        "shortcut_daily_caption": "按 build -> test -> contract/invariant -> hotspot 收口并打开中文控制台。",
        "shortcut_targets": "目标仓巡检",
        "shortcut_targets_command": ".\\run.ps1 daily -Mode quick",
        "shortcut_targets_caption": "对 active targets 执行快速 daily flow。",
        "shortcut_rules": "规则漂移检查",
        "shortcut_rules_command": ".\\run.ps1 rules-check",
        "shortcut_rules_caption": "只检查 agent 规则漂移。",
        "shortcut_feedback": "功能反馈汇总",
        "shortcut_feedback_command": ".\\run.ps1 feedback",
        "shortcut_feedback_caption": "汇总 host feedback、规则同步和自演化证据。",
        "run_now": "执行",
        "command_label": "命令",
        "open_surface": "打开面板",
        "surface_current": "当前面板",
        "runtime_surface_caption": "任务、执行输出、下一步建议和本仓维护状态。",
        "continuity_surface_caption": "跨 host 共享上下文、handoff 和敏感边界。",
        "feedback_surface_caption": "host feedback、自演化状态和处理建议。",
        "surface_loading": "正在加载摘要…",
        "surface_runtime_summary": "任务 {tasks} · 审批 {approvals} · 验证 {verification}",
        "surface_runtime_detail": "查看本仓执行输出、维护策略和下一步建议。",
        "surface_runtime_action": "在此查看执行输出、历史和下一步建议。",
        "surface_continuity_action": "去连续性面板查看共享记录和 secret-blocked 边界。",
        "surface_feedback_action": "去反馈面板查看证据、建议和详细报告。",
        "maintenance": "维护与升级",
        "stage": "阶段",
        "compatibility": "兼容性",
        "upgrade": "升级",
        "triage": "分流",
        "deprecation": "弃用",
        "retirement": "退役",
        "no_tasks": "暂无运行记录。",
        "no_attachments": "暂无已接入目标仓记录。",
        "task": "任务",
        "state": "状态",
        "goal": "目标",
        "outputs": "结果与记录",
        "run": "运行",
        "workspace": "工作区",
        "interaction": "交互",
        "rollback": "回滚",
        "repo": "仓库",
        "adapter": "接入方式",
        "diagnostics": "问题说明",
        "binding": "接入标识",
        "light_pack": "轻量上下文包",
        "fail_closed": "风险自动阻断",
        "preference": "默认方式",
        "gate_profile": "验证档位",
        "reason": "原因",
        "remediation": "修复建议",
        "missing": "缺失",
        "none": "无",
        "not_recorded": "未记录",
        "unknown_repo": "未知仓库",
        "actions": "统一操作台",
        "settings": "执行参数",
        "recommended_next": "AI 推荐下一步",
        "quick_actions": "本仓验证",
        "target_actions": "目标仓治理",
        "rule_actions": "规则与演进",
        "advanced_settings": "高级参数",
        "page_actions": "页面",
        "language": "语言",
        "target": "目标仓",
        "all_targets": "全部目标仓",
        "target_selection": "目标仓选择",
        "target_selection_hint": "默认全部；可改为多选目标仓。",
        "mode": "验证模式",
        "parallelism": "目标并发",
        "fail_fast": "失败即停",
        "dry_run": "只预演",
        "apply_removal": "真实执行清理/卸载",
        "apply_removal_hint": "勾选后才会真实清理/卸载；只预演不删除。",
        "milestone": "里程碑标签",
        "refresh": "刷新状态",
        "run": "执行",
        "command_output": "执行输出",
        "panel_cache_state": "数据状态",
        "panel_cache_cold": "等待手动刷新",
        "panel_cache_cached": "缓存快照",
        "panel_cache_refreshing": "刷新中",
        "panel_cache_ready": "已刷新",
        "panel_cache_error": "刷新失败",
        "history": "执行历史",
        "no_history": "暂无执行历史。",
        "clear_history": "清空历史",
        "runtime_view": "Runtime",
        "feedback_view": "反馈",
        "continuity_view": "连续性",
        "continuity_console": "共享上下文连续性",
        "continuity_caption": "显示 runtime-owned continuity index；不会读取或展示原始凭据、cookie 或完整 transcript。",
        "continuity_refresh": "刷新连续性",
        "continuity_status": "连续性状态",
        "continuity_class": "连续性分类",
        "continuity_empty": "暂无可共享连续性记录。",
        "feedback_console": "功能反馈闭环",
        "feedback_refresh": "刷新反馈摘要",
        "feedback_status": "反馈状态",
        "feedback_generated_at": "生成时间",
        "feedback_summary_caption": "简版摘要",
        "feedback_dimensions": "维度状态",
        "feedback_recommendations": "优化建议",
        "feedback_latest_runs": "最新目标仓证据",
        "feedback_latest_runs_hint": "重点看 3 项：接入、闭环、写入。",
        "feedback_repo_attach": "接入方式",
        "feedback_repo_flow": "运行流",
        "feedback_repo_closure": "闭环状态",
        "feedback_repo_write": "写入状态",
        "feedback_repo_attach_native": "原生直连",
        "feedback_repo_attach_bridge": "桥接接入",
        "feedback_repo_attach_manual": "人工接力",
        "feedback_repo_flow_live": "宿主内直接运行",
        "feedback_repo_flow_bridge": "通过桥接运行",
        "feedback_repo_closure_ready": "已具备闭环",
        "feedback_repo_closure_partial": "闭环未完成",
        "feedback_repo_write_unknown": "未记录写入执行",
        "feedback_repo_write_done": "已执行写入",
        "feedback_links": "文档与报告",
        "feedback_open_report": "查看详细报告",
        "feedback_open_guide": "查看反馈指南",
        "feedback_open_guide_en": "查看英文指南",
        "feedback_report_missing": "尚未生成详细报告，可先执行“功能反馈汇总”。",
        "feedback_loading": "正在加载反馈摘要…",
        "feedback_empty": "暂未获取到反馈摘要。",
        "feedback_preview": "文档预览",
        "feedback_preview_idle": "点击“查看详细报告”或“查看反馈指南”后，会在这里展开内容。",
        "self_evolution_recommendations": "自演化建议",
        "self_evolution_refresh": "刷新自演化建议",
        "self_evolution_status": "自演化状态",
        "self_evolution_generated_at": "报告日期",
        "self_evolution_next_action": "推荐下一步",
        "self_evolution_selector": "selector 判定",
        "self_evolution_readiness": "自更新就绪",
        "self_evolution_variant_count": "候选 variants",
        "self_evolution_blocked": "物化阻断",
        "self_evolution_guard": "变更守卫",
        "self_evolution_trigger": "主动触发",
        "self_evolution_open_report": "查看自演化报告",
        "self_evolution_report_missing": "尚未生成自演化建议报告；可执行“自演化建议”。",
        "self_evolution_loading": "正在加载自演化建议…",
        "self_evolution_empty": "暂无自演化建议。",
        "self_evolution_view_json": "查看 recommendation JSON",
        "self_evolution_promotion_title": "自演化晋升控制器",
        "self_evolution_promotion_refresh": "刷新晋升状态",
        "self_evolution_promotion_status": "晋升状态",
        "self_evolution_promotion_stage": "晋升阶段",
        "self_evolution_promotion_contract": "契约校验",
        "self_evolution_promotion_effective": "有效变更",
        "self_evolution_promotion_open_report": "查看晋升报告",
        "self_evolution_promotion_report_missing": "尚未生成晋升控制器报告；可执行“自演化晋升控制器”。",
        "self_evolution_promotion_loading": "正在加载晋升状态…",
        "self_evolution_promotion_empty": "暂无晋升链路状态。",
        "self_evolution_promotion_view_json": "查看 promotion JSON",
        "ready": "就绪",
        "running": "执行中",
        "static_snapshot": "只读快照",
        "targets_action": "目标仓列表",
        "fast_feedback_action": "快速反馈",
        "readiness_action": "本仓 readiness",
        "codex_guard_absence_action": "旧 guard 缺席检查",
        "rules_dry_run_action": "只查规则漂移",
        "rules_apply_action": "同步规则文件",
        "governance_baseline_action": "下发治理基线",
        "daily_all_action": "运行 Daily 巡检",
        "apply_all_action": "应用全部治理能力",
        "cleanup_targets_action": "一键清理退役文件",
        "uninstall_governance_action": "一键卸载治理",
        "feedback_report_action": "功能反馈汇总",
        "self_evolution_recommend_action": "自演化建议",
        "self_evolution_promotion_action": "自演化晋升控制器",
        "evolution_review_action": "演进候选预演",
        "experience_review_action": "经验沉淀预演",
        "evolution_materialize_action": "物化演进候选",
        "core_principle_action": "核心原则候选",
        "view_ref": "查看",
        "confirm_mutating": "该操作会应用目标仓治理能力，并默认删除已证明安全的退役托管文件；不安全候选会阻断。继续执行？",
        "confirm_evolution_materialize": "将把低风险演进候选物化为 proposal 或禁用态 skill candidate，不启用技能。继续执行？",
        "confirm_managed_cleanup": "将对选中的目标仓执行退役治理文件清理；未勾选“实际删除”时只预演。继续执行？",
        "confirm_governance_uninstall": "将对选中的目标仓执行治理卸载；勾选“实际删除”会删除或修补受管文件并写备份。继续执行？",
        "no_target_selected": "至少选择一个目标仓。",
        "interactive_required": "当前是静态快照；启动本地服务后可执行操作。",
    },
    "en": {
        "html_lang": "en",
        "title": "Governed Runtime Operator Console",
        "runtime_root": "Runtime root",
        "persistence": "Persistence",
        "summary_aria": "Runtime Summary",
        "tasks": "Tasks",
        "tasks_caption": "recent tasks",
        "approvals": "Approvals",
        "approvals_caption": "waiting",
        "verification": "Verification",
        "verification_caption": "verification records",
        "stage_metric_caption": "maintenance stage",
        "attachments": "Attachments",
        "fail_closed_caption": "risk auto-block",
        "workspace_overview": "Workbench Overview",
        "workspace_overview_caption": "Run on the left; this panel shows only key status.",
        "shortcut_entry": "Recommended Entrypoints",
        "shortcut_entry_caption": "Use these entrypoints for repo-local closure; page buttons delegate through the same repository-root command.",
        "shortcut_fast": "Daily fast feedback",
        "shortcut_fast_command": ".\\run.ps1 fast",
        "shortcut_fast_caption": "Run build plus quick feedback tests while coding; delivery still needs readiness.",
        "shortcut_daily": "Delivery readiness",
        "shortcut_daily_command": ".\\run.ps1 readiness -OpenUi",
        "shortcut_daily_caption": "Close with build -> test -> contract/invariant -> hotspot and open the console.",
        "shortcut_targets": "Target sweep",
        "shortcut_targets_command": ".\\run.ps1 daily -Mode quick",
        "shortcut_targets_caption": "Run quick daily flow for active targets.",
        "shortcut_rules": "Rule drift check",
        "shortcut_rules_command": ".\\run.ps1 rules-check",
        "shortcut_rules_caption": "Check agent rule drift only.",
        "shortcut_feedback": "Feedback summary",
        "shortcut_feedback_command": ".\\run.ps1 feedback",
        "shortcut_feedback_caption": "Summarize host feedback, rule sync, and self-evolution evidence.",
        "run_now": "Run",
        "command_label": "Command",
        "open_surface": "Open panel",
        "surface_current": "Current panel",
        "runtime_surface_caption": "Tasks, execution output, next-work recommendation, and repo-local maintenance state.",
        "continuity_surface_caption": "Cross-host shared context, handoffs, and sensitivity boundaries.",
        "feedback_surface_caption": "Host feedback, self-evolution state, and recommendations.",
        "surface_loading": "Loading summary...",
        "surface_runtime_summary": "Tasks {tasks} · Approvals {approvals} · Verification {verification}",
        "surface_runtime_detail": "Review repo-local output, maintenance policy, and next-work guidance.",
        "surface_runtime_action": "Use Runtime for output, history, and next-work decisions.",
        "surface_continuity_action": "Open Continuity for shared records and secret-blocked boundaries.",
        "surface_feedback_action": "Open Feedback for evidence, recommendations, and reports.",
        "maintenance": "Maintenance and Upgrade",
        "stage": "Stage",
        "compatibility": "Compatibility",
        "upgrade": "Upgrade",
        "triage": "Triage",
        "deprecation": "Deprecation",
        "retirement": "Retirement",
        "no_tasks": "No runtime activity has been recorded.",
        "no_attachments": "No attached target repos recorded.",
        "task": "Task",
        "state": "State",
        "goal": "Goal",
        "outputs": "Results",
        "run": "Run",
        "workspace": "Workspace",
        "interaction": "Interaction",
        "rollback": "Rollback",
        "repo": "Repo",
        "adapter": "Connection",
        "diagnostics": "Issue details",
        "binding": "Connection ID",
        "light_pack": "Light context pack",
        "fail_closed": "Fail closed",
        "preference": "Preference",
        "gate_profile": "Gate profile",
        "reason": "Reason",
        "remediation": "Remediation",
        "missing": "missing",
        "none": "none",
        "not_recorded": "not recorded",
        "unknown_repo": "unknown repo",
        "actions": "Unified Operator Bench",
        "settings": "Run Parameters",
        "recommended_next": "AI Recommended Next Step",
        "quick_actions": "Repo Verification",
        "target_actions": "Target Governance",
        "rule_actions": "Rules and Evolution",
        "advanced_settings": "Advanced Parameters",
        "page_actions": "Page",
        "language": "Language",
        "target": "Target repo",
        "all_targets": "All targets",
        "target_selection": "Target selection",
        "target_selection_hint": "All targets by default; switch to multi-select if needed.",
        "mode": "Mode",
        "parallelism": "Target parallelism",
        "fail_fast": "Fail fast",
        "dry_run": "Dry run",
        "apply_removal": "Apply cleanup/uninstall deletes",
        "apply_removal_hint": "Real cleanup/uninstall requires this checkbox; dry run never deletes.",
        "milestone": "Milestone tag",
        "refresh": "Refresh status",
        "run": "Run",
        "command_output": "Execution output",
        "panel_cache_state": "Data status",
        "panel_cache_cold": "Waiting for manual refresh",
        "panel_cache_cached": "Cached snapshot",
        "panel_cache_refreshing": "Refreshing",
        "panel_cache_ready": "Refreshed",
        "panel_cache_error": "Refresh failed",
        "history": "Run history",
        "no_history": "No run history.",
        "clear_history": "Clear history",
        "runtime_view": "Runtime",
        "feedback_view": "Feedback",
        "continuity_view": "Continuity",
        "continuity_console": "Shared Context Continuity",
        "continuity_caption": "Shows the runtime-owned continuity index without exposing raw credentials, cookies, or full transcripts.",
        "continuity_refresh": "Refresh continuity",
        "continuity_status": "Continuity status",
        "continuity_class": "Continuity class",
        "continuity_empty": "No shared continuity records yet.",
        "feedback_console": "Host Feedback Loop",
        "feedback_refresh": "Refresh feedback summary",
        "feedback_status": "Feedback status",
        "feedback_generated_at": "Generated at",
        "feedback_summary_caption": "Snapshot summary",
        "feedback_dimensions": "Dimension status",
        "feedback_recommendations": "Recommendations",
        "feedback_latest_runs": "Latest target evidence",
        "feedback_latest_runs_hint": "Focus on adapter, closure, and write execution.",
        "feedback_repo_attach": "Adapter",
        "feedback_repo_flow": "Flow",
        "feedback_repo_closure": "Closure",
        "feedback_repo_write": "Write",
        "feedback_repo_attach_native": "native attach",
        "feedback_repo_attach_bridge": "bridge attach",
        "feedback_repo_attach_manual": "manual handoff",
        "feedback_repo_flow_live": "live host run",
        "feedback_repo_flow_bridge": "bridge run",
        "feedback_repo_closure_ready": "closure ready",
        "feedback_repo_closure_partial": "closure incomplete",
        "feedback_repo_write_unknown": "write not recorded",
        "feedback_repo_write_done": "write executed",
        "feedback_links": "Docs and reports",
        "feedback_open_report": "Open detailed report",
        "feedback_open_guide": "Open zh-CN guide",
        "feedback_open_guide_en": "Open English guide",
        "feedback_report_missing": "No detailed report yet. Run the feedback summary action first.",
        "feedback_loading": "Loading feedback summary...",
        "feedback_empty": "Feedback summary is not available yet.",
        "feedback_preview": "Preview",
        "feedback_preview_idle": "Open the detailed report or guide to preview the content here.",
        "self_evolution_recommendations": "Self-Evolution Recommendations",
        "self_evolution_refresh": "Refresh self-evolution",
        "self_evolution_status": "Self-evolution status",
        "self_evolution_generated_at": "Report date",
        "self_evolution_next_action": "Recommended next action",
        "self_evolution_selector": "Selector decision",
        "self_evolution_readiness": "Self-update readiness",
        "self_evolution_variant_count": "Candidate variants",
        "self_evolution_blocked": "Materialization blocked",
        "self_evolution_guard": "Change guard",
        "self_evolution_trigger": "Proactive triggers",
        "self_evolution_open_report": "Open self-evolution report",
        "self_evolution_report_missing": "No self-evolution recommendation report yet. Run the self-evolution action first.",
        "self_evolution_loading": "Loading self-evolution recommendations...",
        "self_evolution_empty": "Self-evolution recommendations are not available yet.",
        "self_evolution_view_json": "View recommendation JSON",
        "self_evolution_promotion_title": "Self-Evolution Promotion Controller",
        "self_evolution_promotion_refresh": "Refresh promotion state",
        "self_evolution_promotion_status": "Promotion status",
        "self_evolution_promotion_stage": "Promotion stage",
        "self_evolution_promotion_contract": "Contract validation",
        "self_evolution_promotion_effective": "Effective change",
        "self_evolution_promotion_open_report": "Open promotion report",
        "self_evolution_promotion_report_missing": "No promotion controller report yet. Run the promotion controller action first.",
        "self_evolution_promotion_loading": "Loading promotion state...",
        "self_evolution_promotion_empty": "Promotion lanes are not available yet.",
        "self_evolution_promotion_view_json": "View promotion JSON",
        "ready": "Ready",
        "running": "Running",
        "static_snapshot": "Read-only snapshot",
        "targets_action": "View targets",
        "fast_feedback_action": "Fast feedback",
        "readiness_action": "Check repo status",
        "codex_guard_absence_action": "Retired guard absence check",
        "rules_dry_run_action": "Rule drift check",
        "rules_apply_action": "Sync rules",
        "governance_baseline_action": "Apply governance baseline",
        "daily_all_action": "Run Daily sweep",
        "apply_all_action": "Apply all governance",
        "cleanup_targets_action": "Clean retired files",
        "uninstall_governance_action": "Uninstall governance",
        "feedback_report_action": "Feedback summary",
        "self_evolution_recommend_action": "Self-evolution recommendations",
        "self_evolution_promotion_action": "Self-evolution promotion controller",
        "evolution_review_action": "Evolution dry run",
        "experience_review_action": "Experience dry run",
        "evolution_materialize_action": "Materialize evolution candidates",
        "core_principle_action": "Core-principle candidates",
        "view_ref": "View",
        "confirm_mutating": "This applies target governance and deletes proven-safe retired managed files by default; unsafe candidates are blocked. Continue?",
        "confirm_evolution_materialize": "This materializes low-risk evolution candidates as proposals or disabled skill candidates. It does not enable skills. Continue?",
        "confirm_managed_cleanup": "Run retired governance file cleanup for the selected targets. It only dry-runs unless apply removal is enabled. Continue?",
        "confirm_governance_uninstall": "Run governance uninstall for the selected targets. Apply removal deletes or patches managed files and writes backups. Continue?",
        "no_target_selected": "Select at least one target repo.",
        "interactive_required": "This is a static snapshot; start the local service to run actions.",
    },
}
